name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact File
        run: echo "; echo 'attacker controlled code'; #" > artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./artifact.txt
