name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact Files
        run: echo "https://api.github.com/user" > artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: api.github.com
          path: ./artifact.txt



